import { Module } from '@nestjs/common';
import {
  MappingController,
  TemplateController,
  AnalyzeTemplateController,
  DataTransformController,
  ReportGeneratorController,
  RagController,
  MappingProfileController,
  CompanyController,
  HwpxController,
  UnifiedGenerateController,
  AttendanceReportController,
  AttendanceRuleController,
} from './interface/http/controllers';
import {
  MappingService,
  TemplateService,
  DataTransformService,
  ReportGeneratorService,
  RagService,
  MappingProfileService,
  HwpxGeneratorService,
  HwpxMappingGraphService,
  UnifiedGeneratorService,
  VerificationGraphService,
  AttendanceMappingService,
  AttendanceCalculationService,
  AttendanceReportGraphService,
} from './application/services';
import {
  HeaderDetectionAgent,
  OrchestratorAgent,
  ValueMatchAgent,
  TemplateLeakAgent,
  PatternAgent,
} from './application/agents';
import {
  GeminiAiMappingAdapter,
  ExceljsParserAdapter,
  PrismaTemplateAdapter,
  OpenAiEmbeddingAdapter,
  PrismaCleanReportAdapter,
  PrismaMappingProfileAdapter,
  HwpxParserAdapter,
  SupabaseStorageAdapter,
  PrismaAttendanceRuleAdapter,
} from './infrastructure/adapters';
import {
  AI_MAPPING_PORT,
  EXCEL_PARSER_PORT,
  TEMPLATE_REPOSITORY_PORT,
  EMBEDDING_PORT,
  CLEAN_REPORT_REPOSITORY_PORT,
  MAPPING_PROFILE_REPOSITORY_PORT,
  FILE_STORAGE_PORT,
  ATTENDANCE_RULE_REPOSITORY_PORT,
} from './application/ports';

@Module({
  controllers: [
    MappingController,
    TemplateController,
    AnalyzeTemplateController,
    DataTransformController,
    ReportGeneratorController,
    RagController,
    MappingProfileController,
    CompanyController,
    HwpxController,
    UnifiedGenerateController,
    AttendanceReportController,
    AttendanceRuleController,
  ],
  providers: [
    MappingService,
    TemplateService,
    DataTransformService,
    ReportGeneratorService,
    RagService,
    MappingProfileService,
    HwpxGeneratorService,
    HwpxMappingGraphService,
    UnifiedGeneratorService,
    VerificationGraphService,
    HwpxParserAdapter,
    GeminiAiMappingAdapter,
    HeaderDetectionAgent,
    OrchestratorAgent,
    ValueMatchAgent,
    TemplateLeakAgent,
    PatternAgent,
    {
      provide: AI_MAPPING_PORT,
      useClass: GeminiAiMappingAdapter,
    },
    {
      provide: EXCEL_PARSER_PORT,
      useClass: ExceljsParserAdapter,
    },
    {
      provide: TEMPLATE_REPOSITORY_PORT,
      useClass: PrismaTemplateAdapter,
    },
    {
      provide: EMBEDDING_PORT,
      useClass: OpenAiEmbeddingAdapter,
    },
    {
      provide: CLEAN_REPORT_REPOSITORY_PORT,
      useClass: PrismaCleanReportAdapter,
    },
    {
      provide: MAPPING_PROFILE_REPOSITORY_PORT,
      useClass: PrismaMappingProfileAdapter,
    },
    {
      provide: FILE_STORAGE_PORT,
      useClass: SupabaseStorageAdapter,
    },
    AttendanceMappingService,
    AttendanceCalculationService,
    AttendanceReportGraphService,
    PrismaAttendanceRuleAdapter,
    {
      provide: ATTENDANCE_RULE_REPOSITORY_PORT,
      useClass: PrismaAttendanceRuleAdapter,
    },
  ],
  exports: [
    MappingService,
    TemplateService,
    DataTransformService,
    ReportGeneratorService,
    RagService,
    MappingProfileService,
    HwpxGeneratorService,
  ],
})
export class ExcelFormatterModule {}
